# Site settings
title: 'Debugging From the Trenches' # Your Title
tagline: 'Breakpoints with a history' # A brief tagline for your site
sidebar_image: /images/trench3.jpg

permalink: /blog/:year/:month/:title.html

# Build settings
markdown: kramdown

timezone: Europe/Helsinki
email: teemu.risikko@gmail.com
description: >
  A blog about debugging, python and history.
url: "https://terisikk.github.io/debugging-from-the-trenches/"
twitter_username: TeemuRisikko
github_username: terisikk
baseurl: debugging-from-the-trenches
